
language: node_js

node_js:
- 8

branches:
  only:
  - master

# before_install:
# - npm install -g gulp

install:
npm install

# before_script:
# - git config --global user.name 'ReAlign'
# - git config --global user.email 'realign@yeah.net'

